version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 5
    groups:
      routine-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "npm"
    directory: "/extension"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:15"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 5
    groups:
      routine-extension-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "wxt"
        versions:
          - ">=0.20.0"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:30"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
